apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource.default.name" . }}-node
  namespace: {{ include "resource.default.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource.default.name" . }}-kube-controllers
  namespace: {{ include "resource.default.namespace" . }}
