version: 2.1
orbs:
  architect: giantswarm/architect@4.25.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "calico-app"
          context: "architect"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-giantswarm-playground-app-catalog
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "calico-app"
          context: "architect"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
